source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'Caishen_Example', :exclusive => true do
  pod 'Caishen', :path => '../'
  pod 'CardIO'
end

target 'Caishen_Tests', :exclusive => true do
  pod 'Caishen', :path => '../'

  
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
	config.build_settings['SWIFT_VERSION'] = '2.3'
    end
  end
end