source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'CardKit_Example', :exclusive => true do
  pod 'CardKit', :path => '../'
  pod 'CardIO'
end

target 'CardKit_Tests', :exclusive => true do
  pod 'CardKit', :path => '../'

  
end
