source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'Caishen_Example', :exclusive => true do
  pod 'Caishen', :path => '../'
  pod 'CardIO'
end

target 'Caishen_Tests', :exclusive => true do
  pod 'Caishen', :path => '../'

  
end
