# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
use_frameworks!

target 'SwiftPaymentKit' do
	pod 'CardKit', :path => '../CardKit'
end

target 'SwiftPaymentKitTests' do
	
end

